module.exports = {
  apps: [
    {
      name: 'flow-ad-streamlit',
      cwd: '/Users/douba/Downloads/GPT插件/flow_ad',
      script: 'scripts/start_streamlit.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      error_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/streamlit-error.log',
      out_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/streamlit-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'flow-ad-api',
      cwd: '/Users/douba/Downloads/GPT插件/flow_ad',
      script: 'scripts/start_api.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      error_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/api-error.log',
      out_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'chrome-cdp',
      cwd: './',
      script: './scripts/start_chrome_cdp.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: false,
      watch: false,
      min_uptime: 10000,
      max_restarts: 3,
      exp_backoff_restart_delay: 5000,
      max_memory_restart: '1G',
      env: {
        PATH: process.env.PATH || '',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/chrome-cdp-error.log',
      out_file: './logs/chrome-cdp-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'dd-math-static',
      cwd: '/Users/douba/Projects/DD-math',
      script: 'python3',
      args: 'server.py',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/dd-math-error.log',
      out_file: './logs/dd-math-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'paperclip-ceo-heartbeat',
      cwd: '/Users/douba/Paper',
      script: 'python3',
      args: 'agents/ceo/heartbeat-executor.py',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '200M',
      env: {
        AGENT_HOME: '/Users/douba/Paper/agents/ceo',
        PAPERCLIP_API_URL: 'http://127.0.0.1:3100',
        PAPERCLIP_API_KEY: process.env.PAPERCLIP_API_KEY || '',
        PAPERCLIP_AGENT_ID: 'e10d392a-2c0a-4d79-9056-2638ef5d47d1',
        PAPERCLIP_COMPANY_ID: '3b7ad0a4-abe6-4747-8b79-e3f557ea8540',
        PAPERCLIP_RUN_ID: process.env.PAPERCLIP_RUN_ID || 'heartbeat-scheduled',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
        PYTHONUNBUFFERED: '1',
      },
      error_file: './logs/paperclip-ceo-heartbeat-error.log',
      out_file: './logs/paperclip-ceo-heartbeat-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'hero-pk-game',
      cwd: './project/Game/Hero-PK/Hero-PK',
      script: 'python3',
      args: '-m http.server 3456',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/hero-pk-game-error.log',
      out_file: './logs/hero-pk-game-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'pm2-dashboard',
      cwd: '/Users/douba/Projects/pm2-swift',
      script: 'scripts/pm2_http_server.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'development',
        VITE_DEV: 'true',
        PM2_DASHBOARD_PORT: '4321',
        PM2_DASHBOARD_HOST: '127.0.0.1',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
        PORT: '4321',
      },
      error_file: '/Users/douba/Projects/pm2-swift/logs/error.log',
      out_file: '/Users/douba/Projects/pm2-swift/logs/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
  ],
};
