module.exports = {
  apps: [
    {
      name: 'xm-pm2-guardian',
      cwd: './',
      script: 'scripts/pm2_guardian.py',
      interpreter: 'python3',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      env: {
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
        // 1分钟一次巡检
        PM2_GUARDIAN_INTERVAL: '60',
        // 5分钟窗口内重启>=3次视为重启风暴
        PM2_GUARDIAN_WINDOW: '300',
        PM2_GUARDIAN_THRESHOLD: '3',
        // 同一服务同一类异常，15分钟内只升级一次AI（避免每分钟创建对话）
        PM2_GUARDIAN_ESCALATION_COOLDOWN: '900',
        // 监控的目标进程列表（加上 habit-atoms-cron）
        // PM2_GUARDIAN_APPS: 'xm-console-api,xm-telegram-bot,xm-pulsar,xm-droid-monitor',
      },
      error_file: './logs/pm2-guardian-error.log',
      out_file: './logs/pm2-guardian-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-console-api',
      cwd: './AI工作区/控制台/backend',
      script: '.venv312/bin/python',
      args: '-m uvicorn main:app --host 0.0.0.0 --port 18920',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        // When console backend imports scripts/heartbeat_service, avoid blocking self-HTTP calls.
        XM_CONSOLE_API_DISABLE_HTTP: '1',
        FACTORY_API_KEY: process.env.FACTORY_API_KEY || '',
        OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
        PATH: process.env.PATH || '',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-console-frontend',
      cwd: './AI工作区/控制台/frontend',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: '15921',
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-telegram-bot',
      cwd: './telegram_ops_bot',
      script: './pm2_start.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: true,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      env: {
        PYTHONPATH: '/Users/douba/Projects/XM/scripts:/Users/douba/Projects/XM',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/bot-error.log',
      out_file: './logs/bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'xm-pulsar',
      cwd: './',
      script: 'pulsar.py',
      interpreter: 'python3',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      env: {
        // 防止误把测试变量带进 PM2 运行环境（若 shell 环境里残留 XM_TEST_CRASH_LOOP=1，会触发自杀重启风暴）
        XM_TEST_CRASH_LOOP: '0',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
        PYTHONUNBUFFERED: '1',
      },
      error_file: './logs/pulsar-error.log',
      out_file: './logs/pulsar-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-digital-human-api',
      cwd: './project/DOUDOU/backend',
      script: '.venv312/bin/python',
      args: '-m uvicorn app.main:app --host 0.0.0.0 --port 18921',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
        PATH: process.env.PATH || '',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/digital-human-error.log',
      out_file: './logs/digital-human-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-digital-human-frontend',
      cwd: './project/DOUDOU/frontend',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: '15922',
      },
      error_file: './logs/digital-human-frontend-error.log',
      out_file: './logs/digital-human-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xhs-spider',
      cwd: './project/Spider_XHS',
      script: './venv/bin/python',
      args: 'app.py',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PATH: process.env.PATH || '',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/xhs-spider-error.log',
      out_file: './logs/xhs-spider-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-droid-monitor',
      cwd: './',
      script: 'scripts/droid_monitor_loop.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      error_file: './logs/droid-monitor-error.log',
      out_file: './logs/droid-monitor-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-checkpoint-extractor',
      cwd: './AI工作区/控制台/backend',
      script: '.venv312/bin/python',
      args: 'services/checkpoint_scheduler.py --daemon --interval 6',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 60000,
      max_restarts: 5,
      max_memory_restart: '200M',
      env: {
        PATH: '/Users/douba/Library/Python/3.9/bin:' + (process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin'),
        HOME: process.env.HOME || '',
      },
      error_file: './logs/checkpoint-extractor-error.log',
      out_file: './logs/checkpoint-extractor-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'hero-pk-game',
      cwd: './project/Game/Hero-PK/Hero-PK',
      script: 'python3',
      args: '-m http.server 3456',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/hero-pk-game-error.log',
      out_file: './logs/hero-pk-game-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-syai-admin-frontend',
      cwd: './project/XM_SYAI/frontend',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: '15923',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/syai-admin-frontend-error.log',
      out_file: './logs/syai-admin-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-syai-admin-backend',
      cwd: './project/XM_SYAI/backend',
      script: '.venv/bin/python',
      args: '-m uvicorn main:app --host 0.0.0.0 --port 18922 --reload',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PYTHONPATH: '/Users/douba/Projects/XM/project/XM_SYAI',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/syai-admin-backend-error.log',
      out_file: './logs/syai-admin-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-syai-chat-client',
      cwd: './project/XM_SYAI/chat-client',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: '15924',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/syai-chat-client-error.log',
      out_file: './logs/syai-chat-client-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-yqa-dashboard',
      cwd: './project/XM_YQA',
      script: 'python3',
      args: '-m http.server 18925',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/yqa-dashboard-error.log',
      out_file: './logs/yqa-dashboard-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-study-ai',
      cwd: './project/study',
      script: 'api_proxy.py',
      interpreter: 'python3',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
        PYTHONUNBUFFERED: '1',
      },
      error_file: './logs/study-ai-error.log',
      out_file: './logs/study-ai-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'flow-ad-streamlit',
      cwd: '/Users/douba/Downloads/GPT插件/flow_ad',
      script: 'scripts/start_streamlit.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      error_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/streamlit-error.log',
      out_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/streamlit-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'flow-ad-api',
      cwd: '/Users/douba/Downloads/GPT插件/flow_ad',
      script: 'scripts/start_api.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      error_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/api-error.log',
      out_file: '/Users/douba/Downloads/GPT插件/flow_ad/logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-ai-config-backend',
      cwd: './project/AI-Config/web-config-ui',
      script: './server-v3.js',
      interpreter: 'node',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: '60s',
      max_restarts: 10,
      exp_backoff_restart_delay: 5000,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: '18930',
      },
      error_file: './logs/ai-config-backend-error.log',
      out_file: './logs/ai-config-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'xm-ai-config-frontend',
      cwd: './project/AI-Config/web-config-ui',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: '15930',
      },
      error_file: './logs/ai-config-frontend-error.log',
      out_file: './logs/ai-config-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'chrome-cdp',
      cwd: './',
      script: './scripts/start_chrome_cdp.sh',
      interpreter: 'bash',
      instances: 1,
      autorestart: false,
      watch: false,
      min_uptime: 10000,
      max_restarts: 3,
      exp_backoff_restart_delay: 5000,
      max_memory_restart: '1G',
      env: {
        PATH: process.env.PATH || '',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/chrome-cdp-error.log',
      out_file: './logs/chrome-cdp-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'dd-math-static',
      cwd: '/Users/douba/Projects/DD-math',
      script: 'python3',
      args: 'server.py',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'production',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: './logs/dd-math-error.log',
      out_file: './logs/dd-math-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'paperclip-ceo-heartbeat',
      cwd: '/Users/douba/Paper',
      script: 'python3',
      args: 'agents/ceo/heartbeat-executor.py',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '200M',
      env: {
        AGENT_HOME: '/Users/douba/Paper/agents/ceo',
        PAPERCLIP_API_URL: 'http://127.0.0.1:3100',
        PAPERCLIP_API_KEY: process.env.PAPERCLIP_API_KEY || '',
        PAPERCLIP_AGENT_ID: 'e10d392a-2c0a-4d79-9056-2638ef5d47d1',
        PAPERCLIP_COMPANY_ID: '3b7ad0a4-abe6-4747-8b79-e3f557ea8540',
        PAPERCLIP_RUN_ID: process.env.PAPERCLIP_RUN_ID || 'heartbeat-scheduled',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
        PYTHONUNBUFFERED: '1',
      },
      error_file: './logs/paperclip-ceo-heartbeat-error.log',
      out_file: './logs/paperclip-ceo-heartbeat-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'XM-bazi-backend',
      cwd: '/Users/douba/Projects/XM/project/bazi/backend',
      script: '.venv/bin/python',
      args: '-m uvicorn app.main:app --host 0.0.0.0 --port 18923 --reload',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PYTHONPATH: '/Users/douba/Projects/XM/project/bazi/backend',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: '/Users/douba/Projects/XM/project/bazi/logs/bazi-backend-error.log',
      out_file: '/Users/douba/Projects/XM/project/bazi/logs/bazi-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'XM-bazi-frontend',
      cwd: '/Users/douba/Projects/XM/project/bazi/frontend',
      script: 'npm',
      args: 'run dev',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PORT: '15926',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
      },
      error_file: '/Users/douba/Projects/XM/project/bazi/logs/bazi-frontend-error.log',
      out_file: '/Users/douba/Projects/XM/project/bazi/logs/bazi-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'web-share',
      cwd: '/Users/douba/Projects/XM/project/WEB-share',
      script: '/opt/homebrew/Cellar/node@22/22.22.0/bin/node',
      args: './node_modules/vite/bin/vite.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '200M',
      env: {
        NODE_ENV: 'development',
        PORT: '42069',
        npm_node_execpath: '/opt/homebrew/Cellar/node@22/22.22.0/bin/node',
      },
      error_file: '/Users/douba/Projects/XM/project/WEB-share/logs/web-share-error.log',
      out_file: '/Users/douba/Projects/XM/project/WEB-share/logs/web-share-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'subform',
      cwd: '/Users/douba/Projects/XM/project/subform',
      script: 'npx',
      args: 'serve -s . -l 7373',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/Users/douba/Projects/XM/project/subform/logs/error.log',
      out_file: '/Users/douba/Projects/XM/project/subform/logs/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'xm-dashboard-framework',
      cwd: '/Users/douba/Projects/XM/project/QuickBI/dashboard-framework',
      script: './start.sh',
      interpreter: 'bash',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      min_uptime: 10000,
      max_restarts: 10,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'development',
        PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
        HOME: process.env.HOME || '',
        PORT: '38430',
      },
      error_file: '/Users/douba/Projects/XM/project/QuickBI/dashboard-framework/logs/error.log',
      out_file: '/Users/douba/Projects/XM/project/QuickBI/dashboard-framework/logs/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
  ],
};
